import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  BarChart3,
  Bus,
  Calendar,
  Car,
  CheckCircle,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  FileText,
  Heart,
  MapPin,
  MessageSquareWarning,
  Package,
  Puzzle,
  Shield,
  ShieldAlert,
  Star,
  TrendingUp,
  UserCheck,
  UserRound,
  Users,
  UserX,
  Wallet,
  XCircle,
} from 'lucide-react';

/** Fallback icons for AdminMetricGrid when a card omits an explicit icon. */
const METRIC_ICON_BY_LABEL: Record<string, LucideIcon> = {
  'total users': Users,
  parents: UserRound,
  'driver applicants': FileText,
  'approved drivers': Car,
  admins: Shield,
  'total riders': Users,
  active: CheckCircle,
  'special needs': Heart,
  'with subscriptions': Bus,
  'open reports': AlertTriangle,
  'under review': Shield,
  resolved: CheckCircle,
  'high severity': XCircle,
  pending: Clock,
  approved: CheckCircle,
  rejected: XCircle,
  'needs changes': AlertCircle,
  'total revenue': DollarSign,
  'paid payments': TrendingUp,
  'pending revenue': Clock,
  'pending payments': CreditCard,
  'failed payments': XCircle,
  'wallet top-ups': Wallet,
  'subscription revenue': CreditCard,
  'total wallet balance': Wallet,
  'pending payment': CreditCard,
  cancelled: XCircle,
  'unassigned driver': UserX,
  'expiring soon': Clock,
  'active drivers': UserCheck,
  suspended: AlertTriangle,
  'available now': Car,
  'avg rating': Star,
  'trips (page)': Clock,
  'total events': ClipboardList,
  today: Calendar,
  'critical / admin': ShieldAlert,
  'active packages': Package,
  'active add-ons': Puzzle,
  'inactive items': Archive,
  'trips today': Calendar,
  unassigned: UserX,
  delayed: Clock,
  'gps stale': MapPin,
  'chat flags': MessageSquareWarning,
  completed: CheckCircle,
};

export function resolveAdminMetricIcon(label: string, explicit?: LucideIcon): LucideIcon {
  if (explicit) return explicit;
  return METRIC_ICON_BY_LABEL[label.toLowerCase()] ?? BarChart3;
}
